In [8]:
import sqlite3

In [9]:
db=sqlite3.connect('student_database.db')

In [10]:
cursor=db.cursor()

In [11]:
r=cursor.execute('select * from stud_det')

In [12]:
for n in r:
    print(n)

(9988776604, 'Salah', '03-10-2020', 85)
(9988776605, 'Heung-Son', '21-06-2020', 39)
(9988776606, 'Ronaldo', '08-05-2020', 86)
(9988776607, 'Kane', '11-05-2022', 57)
(9988776608, 'Mane', '17-05-2022', 52)
(6609998877, 'Vardy', '17-12-2020', 54)
(6609998878, 'Jota', '06-11-2021', 45)
(6609998879, 'Bruyne', '26-11-2020', 49)
(6609998880, 'Zaha', '05-12-2020', 88)
(6609998881, 'Sterling', '29-10-2020', 61)
(9988776614, 'Toney', '31-03-2022', 71)
(9988776615, 'Maddison', '10-03-2020', 44)
(1687799866, 'Bowen', '14-02-2021', 96)
(1687799867, 'Saka', '19-12-2022', 92)
(1687799868, 'Watkins', '30-01-2021', 49)
(1687799869, 'Mount', '16-09-2022', 48)
(1687799870, 'Raphael', '15-05-2021', 50)
(1687799871, 'Mahrez', '30-10-2021', 72)
(9988776622, 'Pukki', '19-02-2021', 93)
(9988776623, 'Fernandes', '01-03-2022', 94)


In [13]:

while True:
    try:
        phn_num=int(input('please enter your mobile number'))
        if len(str(phn_num))!=10:
            print('number should be of 10 digits')
            continue
        else:
            r=cursor.execute('select * from stud_det')
            for n in r:
                if n[0]==phn_num:
                    print('name',n[1])
                    print('DOJ',n[2])
                    print('marks',n[3])
                    break
                    
                    
            else:
                print('record not found in database')
                continue
                    
                    
            break
    except:
        print('phone number should be numeric')
        continue

please enter your mobile number7765432
number should be of 10 digits
please enter your mobile number1234567890
record not found in database
please enter your mobile number9988776605
name Heung-Son
DOJ 21-06-2020
marks 39


#  Numpy

In [2]:
import numpy


In [3]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [4]:
import numpy as np

In [5]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [6]:
np.sqrt(10)

3.1622776601683795

In [8]:
np.sqrt(9)

3.0

In [14]:
n=(10,987,90,40,89,210,934,43,80)

In [15]:
type(n)

tuple

In [18]:
print(np.amin([45,76,89,15,65,87]))

15


In [22]:
print(np.amax([45,76,89,15,65,87]))

89


In [24]:
np.ceil(30.5)

31.0

In [27]:
np.sqrt(np.ceil(8.8))

3.0

In [28]:
np.ceil(np.sqrt(10))

4.0

In [29]:
a=np.ceil(65.097)

In [30]:
b=np.sqrt(10)

In [31]:
np.sum(a+b)

69.16227766016839

In [32]:
print(a)

66.0


In [33]:
print(b)

3.1622776601683795


In [34]:
np.ceil(np.sum(a+b))

70.0

In [35]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [38]:
q=np.sqrt([5,10,15])

In [39]:
print(q)

[2.23606798 3.16227766 3.87298335]


In [41]:
np.sum([2.23606798, 3.16227766, 3.87298335])

9.27132899

In [42]:
np.ceil(9.27132899)

10.0

In [44]:
np.array([5,9,13,45])

array([ 5,  9, 13, 45])

In [45]:
qwe=np.array([5,9,13,45])

In [46]:
type(qwe)

numpy.ndarray

In [47]:
b=np.asarray(qwe)

In [48]:
print(b)

[ 5  9 13 45]


In [49]:
type(b)

numpy.ndarray

In [53]:
np.asarray((qwe),dtype=float)

array([ 5.,  9., 13., 45.])

In [55]:
np.array([1,4,7,0,5],dtype=float)

array([1., 4., 7., 0., 5.])

In [91]:
matrix=[[23,14,76,89,90,46],[12,45,76,1,3,2],[35,76,56,45,23,89]]

In [92]:
type(matrix)

list

In [93]:
mat=np.array(matrix)

In [94]:
print('type of object ',type(mat))

type of object  <class 'numpy.ndarray'>


In [95]:
print('here is the matrix','\n' ,mat)

here is the matrix 
 [[23 14 76 89 90 46]
 [12 45 76  1  3  2]
 [35 76 56 45 23 89]]


In [96]:
print('dimensions of matrix',mat.ndim)

dimensions of matrix 2


In [97]:
print('size of matrix',mat.size)

size of matrix 18


In [98]:
print('shape of matrix',mat.shape)

shape of matrix (3, 6)


In [99]:
print('data type of matrix',mat.dtype)

data type of matrix int32


In [100]:
print('type of object ',type(mat))
print('here is the matrix','\n' ,mat)
print('dimensions of matrix',mat.ndim)
print('size of matrix',mat.size)
print('shape of matrix',mat.shape)
print('data type of matrix',mat.dtype)

type of object  <class 'numpy.ndarray'>
here is the matrix 
 [[23 14 76 89 90 46]
 [12 45 76  1  3  2]
 [35 76 56 45 23 89]]
dimensions of matrix 2
size of matrix 18
shape of matrix (3, 6)
data type of matrix int32


In [101]:
list(range(2,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [106]:
a=np.arange(2,10.5,.2)

In [107]:
print(a)

[ 2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6
  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4
  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2
 10.4]


In [108]:
a[::-1]

array([10.4, 10.2, 10. ,  9.8,  9.6,  9.4,  9.2,  9. ,  8.8,  8.6,  8.4,
        8.2,  8. ,  7.8,  7.6,  7.4,  7.2,  7. ,  6.8,  6.6,  6.4,  6.2,
        6. ,  5.8,  5.6,  5.4,  5.2,  5. ,  4.8,  4.6,  4.4,  4.2,  4. ,
        3.8,  3.6,  3.4,  3.2,  3. ,  2.8,  2.6,  2.4,  2.2,  2. ])

In [111]:
print(np.arange(50,0,-5))

[50 45 40 35 30 25 20 15 10  5]


In [119]:
print(np.linspace(10,40,5))

[10.  17.5 25.  32.5 40. ]


In [122]:
print(np.linspace(3,30,9,endpoint=False))

[ 3.  6.  9. 12. 15. 18. 21. 24. 27.]


In [126]:
print(np.linspace(0,99,8,endpoint=False,retstep=True))

(array([ 0.   , 12.375, 24.75 , 37.125, 49.5  , 61.875, 74.25 , 86.625]), 12.375)


In [127]:
print(12.375-24.75)

-12.375


In [128]:
np.array([14,32,76,79])

array([14, 32, 76, 79])

In [132]:
print(np.arange(24,76,3))

[24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75]


In [134]:
print(np.linspace(5,84,32))

[ 5.          7.5483871  10.09677419 12.64516129 15.19354839 17.74193548
 20.29032258 22.83870968 25.38709677 27.93548387 30.48387097 33.03225806
 35.58064516 38.12903226 40.67741935 43.22580645 45.77419355 48.32258065
 50.87096774 53.41935484 55.96774194 58.51612903 61.06451613 63.61290323
 66.16129032 68.70967742 71.25806452 73.80645161 76.35483871 78.90322581
 81.4516129  84.        ]


In [135]:
print(np.linspace(5,84,32,endpoint=False ,retstep=True))

(array([ 5.     ,  7.46875,  9.9375 , 12.40625, 14.875  , 17.34375,
       19.8125 , 22.28125, 24.75   , 27.21875, 29.6875 , 32.15625,
       34.625  , 37.09375, 39.5625 , 42.03125, 44.5    , 46.96875,
       49.4375 , 51.90625, 54.375  , 56.84375, 59.3125 , 61.78125,
       64.25   , 66.71875, 69.1875 , 71.65625, 74.125  , 76.59375,
       79.0625 , 81.53125]), 2.46875)


In [139]:
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [143]:
print(10*np.ones((2,3)))

[[10. 10. 10.]
 [10. 10. 10.]]


In [147]:
s=(np.ones((4,4)))

In [148]:
w=5*(s)

In [150]:
print(w)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [157]:
j=np.arange(30)

In [159]:
print(j)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [165]:
x=np.arange(30).reshape(10,3)

In [166]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


# Random Number Generation

In [175]:
np.random.seed(8)

In [176]:
print(np.random.rand(12,4))

[[0.8734294  0.96854066 0.86919454 0.53085569]
 [0.23272833 0.0113988  0.43046882 0.40235136]
 [0.52267467 0.4783918  0.55535647 0.54338602]
 [0.76089558 0.71237457 0.6196821  0.42609177]
 [0.28907503 0.97385524 0.33377405 0.21880106]
 [0.06580839 0.98287055 0.12785571 0.32213079]
 [0.07094284 0.22476994 0.39363491 0.896145  ]
 [0.34546161 0.98474944 0.02873205 0.35168474]
 [0.38095889 0.76416013 0.93880391 0.3196898 ]
 [0.43247593 0.27014574 0.80105589 0.63823881]
 [0.06869013 0.60364448 0.79557456 0.03200816]
 [0.45544782 0.79017254 0.98859652 0.58396454]]


In [177]:
print(np.random.seed(43))

None


In [178]:
print(np.random.randn(12,4))

[[ 0.25739993 -0.90848143 -0.37850311 -0.5349156 ]
 [ 0.85807335 -0.41300998  0.49818858  2.01019925]
 [ 1.26286154 -0.43921486 -0.34643789  0.45531966]
 [-1.66866271 -0.8620855   0.49291085 -0.1243134 ]
 [ 1.93513629 -0.61844265 -1.04683899 -0.88961759]
 [ 0.01404054 -0.16082969  2.23035965 -0.39911572]
 [ 0.05444456  0.88418182 -0.10798056  0.55560698]
 [ 0.39490664  0.83720502 -1.40787817  0.80784941]
 [-0.13828364  0.18717859 -0.38665814  1.65904873]
 [-2.04706913  1.39931699 -0.67900712  1.52898513]
 [ 1.22121596  1.01498852  0.82812998  2.26629271]
 [-0.59495567 -0.58126954 -0.65589415  0.92514885]]


In [184]:
print(np.random.randint(4,22,4))

[12  5 12 13]
