In [1]:
import numpy as np

In [2]:
np.random.seed(7)

In [3]:
print(np.random.rand(3,3))

[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]]


In [4]:
print(np.random.randn(3,3))

[[ 2.02577152e+00 -1.32805048e-03 -4.76931700e-01]
 [ 1.21673235e+00 -1.63132075e-01 -3.34237590e-01]
 [-1.49682070e-02  2.13906749e-02  7.48781076e-01]]


In [5]:
print(np.random.randint(1,4,5))

[2 1 2 1 3]


In [6]:
print(np.random.randint(1,3000,(7,8)))

[[ 313 2250 1487 2599  773 2543 1162 1220]
 [ 945  258 1729 2449 1952 1374 2989 2653]
 [ 765 1608 2328 2794 2852 1473 1342 1416]
 [1176   93  760 1249 1686 2405  932 2530]
 [2628 1244  482 1044 2972  788   34 1311]
 [2790 1866  990 2002 1920 1440 1155 1108]
 [ 403 2070 1656 2252 1979   48  785 2573]]


In [7]:
while True:
    otp=np.random.randint(1000,10000,1)
    print('your OTp is:-',otp)
    user_otp=int(input('please enter you otp here'))
    if user_otp==otp:
        print('you are successfully logged in')
        break
    else:
        print('please enter correct OTP')
        

your OTp is:- [1349]
please enter you otp here1349
you are successfully logged in


In [8]:
while True:
    try:
        otp=np.random.randint(1000,10000,1)
        print('your OTp is:-',otp)
        user_otp=int(input('please enter you otp here'))
        if user_otp==otp:
            print('you are successfully logged in')
            break
        else:
            print('please enter correct OTP')
            continue
    except:
        print('OTP is integer only')

your OTp is:- [8913]
please enter you otp herefgh
OTP is integer only
your OTp is:- [5489]
please enter you otp here21478
please enter correct OTP
your OTp is:- [1844]
please enter you otp here1844
you are successfully logged in


In [9]:
import numpy as np

In [10]:
from numpy.random import randint as ri

In [11]:
a=ri(30,200,20)

In [12]:
print(a)

[ 97 140 172 154  50  83 173  89  65  78  34  73  84  73  69 161 187 170
 109  59]


In [13]:
x=a.reshape(4,5)

In [14]:
x

array([[ 97, 140, 172, 154,  50],
       [ 83, 173,  89,  65,  78],
       [ 34,  73,  84,  73,  69],
       [161, 187, 170, 109,  59]])

In [15]:
print(np.median(x))

86.5


In [16]:
print(a.min())

34


In [17]:
print(a.max())

187


In [18]:
print(np.min(x))

34


In [19]:
print(np.max(x))

187


In [20]:
print(np.mean(a))

106.0


In [21]:
print(a.mean())

106.0


In [22]:
print(np.sort(x))

[[ 50  97 140 154 172]
 [ 65  78  83  89 173]
 [ 34  69  73  73  84]
 [ 59 109 161 170 187]]


In [23]:
print(np.sort(x,axis=0))

[[ 34  73  84  65  50]
 [ 83 140  89  73  59]
 [ 97 173 170 109  69]
 [161 187 172 154  78]]


In [24]:
q=ri(100,999,40)

In [25]:
print(q)

[748 666 778 473 810 761 144 747 821 595 297 200 280 269 129 382 932 864
 290 826 838 112 746 588 543 206 722 984 597 449 586 334 629 105 947 149
 538 432 717 282]


In [26]:
w=q.reshape(5,8)

In [27]:
print(w)

[[748 666 778 473 810 761 144 747]
 [821 595 297 200 280 269 129 382]
 [932 864 290 826 838 112 746 588]
 [543 206 722 984 597 449 586 334]
 [629 105 947 149 538 432 717 282]]


In [28]:
print(np.sort(w))

[[144 473 666 747 748 761 778 810]
 [129 200 269 280 297 382 595 821]
 [112 290 588 746 826 838 864 932]
 [206 334 449 543 586 597 722 984]
 [105 149 282 432 538 629 717 947]]


In [29]:
print(np.sort(w,axis=0))

[[543 105 290 149 280 112 129 282]
 [629 206 297 200 538 269 144 334]
 [748 595 722 473 597 432 586 382]
 [821 666 778 826 810 449 717 588]
 [932 864 947 984 838 761 746 747]]


In [30]:
r=np.sort(w)

In [31]:
print(r)

[[144 473 666 747 748 761 778 810]
 [129 200 269 280 297 382 595 821]
 [112 290 588 746 826 838 864 932]
 [206 334 449 543 586 597 722 984]
 [105 149 282 432 538 629 717 947]]


In [32]:
print(np.sort(r,axis=0))

[[105 149 269 280 297 382 595 810]
 [112 200 282 432 538 597 717 821]
 [129 290 449 543 586 629 722 932]
 [144 334 588 746 748 761 778 947]
 [206 473 666 747 826 838 864 984]]


## numpy conditions


In [33]:
emp_salary=np.random.randint(10,50,10)

In [34]:
print(emp_salary)

[47 19 33 31 14 37 22 21 16 43]


In [35]:
print(np.where(emp_salary<25))

(array([1, 4, 6, 7, 8], dtype=int64),)


In [36]:
emp_salary[np.where(emp_salary<25)]

array([19, 14, 22, 21, 16])

In [37]:
np.clip(emp_salary,a_min=20,a_max=50)

array([47, 20, 33, 31, 20, 37, 22, 21, 20, 43])

In [38]:
c=np.random.randint(15,80,15)

In [39]:
print(c)

[45 71 66 70 27 51 73 56 30 58 74 78 43 31 20]


In [40]:
print(np.min(c))

20


In [41]:
print(c.min())

20


In [42]:
print(np.max(c))

78


In [43]:
print(c.max())

78


In [44]:
print(np.where(c<25))

(array([14], dtype=int64),)


In [45]:
print(np.where(c>50))

(array([ 1,  2,  3,  5,  6,  7,  9, 10, 11], dtype=int64),)


In [46]:
c[np.where(c<25)]

array([20])

In [47]:
np.clip(c,a_min=20,a_max=50)

array([45, 50, 50, 50, 27, 50, 50, 50, 30, 50, 50, 50, 43, 31, 20])

In [48]:
ar=np.arange(10,30)

In [49]:
print(ar)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [50]:
print(ar[7])

17


In [51]:
print(ar(7))

TypeError: 'numpy.ndarray' object is not callable

In [52]:
print(ar.max())

29


In [53]:
print(ar[19])

29


In [54]:
print(ar[[2,4,6,8,10]])

[12 14 16 18 20]


In [55]:
ad=np.arange(1,10)

In [56]:
print(ad)

[1 2 3 4 5 6 7 8 9]


In [57]:
ad.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
q=ad.reshape(3,3)

In [59]:
print(q)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
q[1][2]

6

In [61]:
q[1]

array([4, 5, 6])

In [62]:
q[1:,:2]

array([[4, 5],
       [7, 8]])

In [63]:
q[1:2,[1,2]]

array([[5, 6]])

In [64]:
q[0,1]=35

In [65]:
print(q)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


In [66]:
q[1,0]=100

In [67]:
print(q)

[[  1  35   3]
 [100   5   6]
 [  7   8   9]]


In [68]:
m=np.random.randint(10,100,15)

In [69]:
print(m)

[45 87 42 97 43 55 50 24 55 52 44 65 28 19 83]


In [70]:
a=m.reshape(3,5)

In [71]:
print(a)

[[45 87 42 97 43]
 [55 50 24 55 52]
 [44 65 28 19 83]]


In [72]:
a>50

array([[False,  True, False,  True, False],
       [ True, False, False,  True,  True],
       [False,  True, False, False,  True]])

In [73]:
a[a>50]

array([87, 97, 55, 55, 52, 65, 83])

In [74]:
no=100
np.where(no>27,'pass','fail')

array('pass', dtype='<U4')

In [75]:
intt=np.random.randint(-10,50,100)

In [76]:
print(intt)

[  3  11  33  -9  21   4   6  38  15  39  36  23  11   9   8 -10   3  48
   0  42  48  17  18  -2  45  23  26  15  34  41  44  32  18  -3  39   5
 -10   8  29  34  38 -10  34  -1  36  46  24  38  33  -5  11   6  31   1
  32  22  30  26  -5  18  33  19  39  36  32  42  38  21  -3  18  37  48
  40  38   4  37   3   9  31   3  14  -7  -3  39  32  22  23   1  17  -6
  28  21  49  39  20   4  34  33   2   6]


In [77]:
np.count_nonzero(intt)

99

In [78]:
q.ravel()

array([  1,  35,   3, 100,   5,   6,   7,   8,   9])

In [79]:
ra=ri(0,20, size=(4,4))

In [80]:
print(ra)

[[17  0 11  1]
 [ 8  1 15  2]
 [12  4 12 11]
 [17 18 18 18]]


In [81]:
ra.ravel()

array([17,  0, 11,  1,  8,  1, 15,  2, 12,  4, 12, 11, 17, 18, 18, 18])

In [82]:
m=np.arange(1,10)

In [83]:
m1=m.reshape(3,3)

In [84]:
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
n=np.arange(11,20)

In [86]:
m2=n.reshape(3,3)

In [87]:
print(m2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [88]:
m1+m1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [89]:
m1*m2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [90]:
m1[1,2]+m2[0,1]

18

In [91]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
start=np.zeros((3,3))

In [93]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [94]:
add_rows=np.array([[1,0,2]])

In [95]:
print(add_rows)

[[1 0 2]]


In [96]:
np.array(start)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
print(start+add_rows)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [98]:
 d=np.ones((3,3))

In [99]:
print(d+add_rows)

[[2. 1. 3.]
 [2. 1. 3.]
 [2. 1. 3.]]


In [100]:
new_rows=add_rows.T

In [101]:
print(new_rows)

[[1]
 [0]
 [2]]


In [102]:
t=start+new_rows

In [103]:
print(t)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [104]:
 new=np.zeros((3,4))

In [105]:
print(new)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [106]:
row=np.array([[2,1,3]])

In [107]:
print(row)

[[2 1 3]]


In [108]:
column=row.T

In [109]:
print(column)

[[2]
 [1]
 [3]]


In [110]:
add=column+new

In [111]:
print(add)

[[2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [3. 3. 3. 3.]]
